Repository gqrx-sdr/gqrx, pull requests merged in 2023-09, with the labels that each got.

#1279 Initialize d_fftWindowType to zero
  src/applications/gqrx/mainwindow.cpp
Labels: bug

#1280 Add support for RTL-SDR Blog V4
  .github/workflows/build.yml
  resources/news.txt
Labels: feature, rtlsdr

#1274 Save FFT plotter center frequency in settings
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: feature

#1271 performance: Improve resampler performance
  resources/news.txt
  src/dsp/resampler_xx.cpp
Labels: performance

#1270 Properly handle smooth scrolling
  resources/news.txt
  src/qtgui/freqctrl.cpp
  src/qtgui/freqctrl.h
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: bug

#1281 Fix inconsistent 1-2-5 scaling of amplitude axis
  resources/news.txt
  src/qtgui/plotter.cpp
Labels: bug

#1283 Add back clamping in band plan coordinate calculation
  src/qtgui/plotter.cpp
Labels: bug

#1284 Shorten band names to fit in narrow spaces
  resources/news.txt
  src/qtgui/plotter.cpp
Labels: feature

#1285 Remove unnecessary clamping checks
  src/qtgui/plotter.cpp
Labels: cleanup

#1288 Don't run FFTs until enough samples have arrived
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/receiver.cpp
  src/applications/gqrx/receiver.h
  src/dsp/rx_fft.cpp
  src/dsp/rx_fft.h
Labels: bug

#1287 Add transparency to plotter overlay elements
  src/qtgui/meter.cpp
  src/qtgui/plotter.cpp
Labels: bug
