Repository gqrx-sdr/gqrx, pull requests merged in 2023-04, with the labels that each got.

#1207 stereo_demod: reduce CPU consumption
  resources/news.txt
  src/dsp/stereo_demod.cpp
Labels: performance

#1206 iq_swap_cc: implement directly instead of as a hier block
  resources/news.txt
  src/dsp/correct_iq_cc.cpp
  src/dsp/correct_iq_cc.h
Labels: performance

#1220 Drop support for GNU Radio 3.7
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  resources/news.txt
  src/CMakeLists.txt
  src/applications/gqrx/receiver.h
  src/dsp/correct_iq_cc.h
  src/dsp/downconverter.h
  src/dsp/filter/fir_decim.cpp
  src/dsp/filter/fir_decim.h
  src/dsp/lpf.h
  src/dsp/rx_filter.h
  src/dsp/rx_rds.cpp
  src/dsp/rx_rds.h
  src/dsp/stereo_demod.h
Labels: cleanup

#1221 Fix loading of narrow FM tau setting
  resources/news.txt
  src/qtgui/demod_options.cpp
Labels: bug

#1043 Store missing demod settings to the config file and restore at startup
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/qtgui/demod_options.cpp
  src/qtgui/demod_options.h
  src/qtgui/dockrxopt.cpp
  src/qtgui/dockrxopt.h
Labels: feature

#1157 Make it possible to control audio gain via the remote interface
  resources/news.txt
  resources/remote-control.txt
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/remote_control.cpp
  src/applications/gqrx/remote_control.h
  src/qtgui/dockaudio.cpp
  src/qtgui/dockaudio.h
Labels: feature

#1188 Redraw panadapter bookmark marks on bookmark adding/deletion/tag selection
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/qtgui/bookmarks.cpp
Labels: bug

#1224 Fix high-DPI rendering of frequency control and S-meter
  resources/news.txt
  src/qtgui/freqctrl.cpp
  src/qtgui/meter.cpp
Labels: bug

#1225 Don't explicitly set button sizes
  src/qtgui/dockaudio.cpp
  src/qtgui/dockaudio.ui
  src/qtgui/dockrxopt.cpp
  src/qtgui/dockrxopt.ui
Labels: cleanup

#1226 Allow dock buttons to be smaller
  src/qtgui/dockaudio.ui
  src/qtgui/dockrxopt.ui
Labels: bug
