Repository gqrx-sdr/gqrx, pull requests merged in 2023-03, with the labels that each got.

#1200 Shortcut key "z" zeros the rx filter offset
  resources/kbd-shortcuts.txt
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/mainwindow.h
Labels: feature

#1176 Remove unnecessary TagInfo constructor (refactor)
  src/qtgui/bookmarks.cpp
  src/qtgui/bookmarks.h
Labels: cleanup

#1201 Make zoom reset more reliable
  resources/news.txt
  src/qtgui/plotter.cpp
Labels: bug
