Repository gqrx-sdr/gqrx, pull requests merged in 2023-06, with the labels that each got.

#1252 Fix buffer overflow in sniffer block
  resources/news.txt
  src/dsp/sniffer_f.cpp
  src/dsp/sniffer_f.h
Labels: bug

#1258 Calculate width of Y axis in saved waterfall
  resources/news.txt
  src/qtgui/plotter.cpp
Labels: bug

#1242 plotter: limit plot update rate
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/qtgui/dockfft.ui
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: performance

#1259 plotter: draw on pixel center for cleaner picture
  src/qtgui/plotter.cpp
Labels: bug

#1260 Fix some more double promotion warnings
  src/qtgui/plotter.cpp
Labels: cleanup

#1261 Fix a double promotion warning in setNewFftData
  src/qtgui/plotter.cpp
Labels: cleanup

#1262 plotter: use volk kernels for some calculations
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: performance

#1263 Switch to float in CPlotter::draw
  CMakeLists.txt
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: cleanup, performance
