Repository gqrx-sdr/gqrx, pull requests merged in 2023-10, with the labels that each got.

#1290 Avoid resetting histogram, min & max unnecessarily
  src/qtgui/plotter.cpp
Labels: bug

#1291 Fix drawing of black areas in waterfall
  src/qtgui/plotter.cpp
Labels: bug

#1292 Fix the pixels/bin calculation
  src/qtgui/plotter.cpp
Labels: bug

#1293 Invalidate max, min, & hist before updateOverlay & redraw
  src/qtgui/plotter.cpp
Labels: bug

#1300 Refactor the signal meter
  src/qtgui/meter.cpp
  src/qtgui/meter.h
Labels: cleanup

#1302 Refactor the frequency control
  src/qtgui/freqctrl.cpp
  src/qtgui/freqctrl.h
Labels: cleanup

#1304 Use a QImage for the waterfall
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: performance

#1182 Allow recording IQ samples in the SigMF format
  README.md
  resources/news.txt
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/mainwindow.h
  src/qtgui/iq_tool.cpp
  src/qtgui/iq_tool.h
  src/qtgui/iq_tool.ui
Labels: feature

#1305 Add core:hw to SigMF metadata files
  src/applications/gqrx/mainwindow.cpp
Labels: feature

#1310 Allow the Qt version to be chosen explicitly
  CMakeLists.txt
  resources/news.txt
Labels: feature
