Repository gqrx-sdr/gqrx, pull requests merged in 2023-05, with the labels that each got.

#1218 Plotter features and refactoring
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/mainwindow.h
  src/applications/gqrx/mainwindow.ui
  src/applications/gqrx/receiver.cpp
  src/applications/gqrx/receiver.h
  src/dsp/rx_fft.cpp
  src/dsp/rx_fft.h
  src/qtgui/dockaudio.cpp
  src/qtgui/dockfft.cpp
  src/qtgui/dockfft.h
  src/qtgui/dockfft.ui
  src/qtgui/plotter.cpp
  src/qtgui/plotter.h
Labels: feature

#1238 Avoid implicit promotion to double in AGC
  src/dsp/agc_impl.cpp
  src/dsp/agc_impl.h
Labels: cleanup, performance

#1239 Avoid implicit promotion to double in noise blanker
  src/dsp/rx_noise_blanker_cc.cpp
Labels: cleanup, performance

#1240 Fix double promotion warnings everywhere except the plotter
  src/applications/gqrx/mainwindow.cpp
  src/applications/gqrx/receiver.cpp
  src/dsp/afsk1200/cafsk12.cpp
  src/dsp/resampler_xx.cpp
  src/dsp/rx_demod_am.cpp
  src/dsp/rx_demod_fm.cpp
  src/dsp/rx_meter.cpp
  src/dsp/stereo_demod.cpp
  src/qtgui/ctk/ctkRangeSlider.cpp
  src/qtgui/demod_options.cpp
  src/qtgui/dockaudio.cpp
  src/qtgui/dockfft.cpp
  src/qtgui/dockrxopt.cpp
  src/qtgui/ioconfig.cpp
  src/qtgui/meter.cpp
  src/qtgui/plotter.h
  src/receivers/nbrx.cpp
  src/receivers/wfmrx.cpp
Labels: cleanup

#1245 Store waterfall span setting in milliseconds
  resources/news.txt
  src/qtgui/dockfft.cpp
  src/qtgui/dockfft.h
Labels: cleanup
